# 头部菜单，title: link
menu:
  Whoami: /whoami
  Github: https://github.com/hongjun500
  归档: /archives
  分类: /categories
  标签云: /tags

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: true

# 默认音乐（随机播放）
mp3: 
    - http://bgm.bhongjun.com/%E4%B9%B0%E8%BE%A3%E6%A4%92%E4%B9%9F%E7%94%A8%E5%88%B8%20-%20%E8%B5%B7%E9%A3%8E%E4%BA%86.mp3

# 首页封面图, 为空时取文章的cover作为封面(注意跨域问题,建议使用同源图片)
welcome_cover: /img/welcome-cover.jpg

# 默认文章封面图（随机调用,支持外链）
cover: 
  - /img/cover.jpg
  - /img/welcome-cover.jpg

 
# 是否使用mathjax
mathjax: false


# 是否关闭默认滚动条
scrollbar: true

# 本地搜索,请将索引文件放在网站根目录,或修改主题js文件的path值
local_search:
    # 是否启用
    enable: true

# 是否显示 一言(hitokoto)
hitokoto: true

# 链接(可选:facebook,twitter,github,wechat,email)
links:
    # facebook: /
    # twitter: /
    github: https://github.com/hongjun500
    wechat: /img/logo.png
    email: bhj.hongjun@qq.com
  
# 备案
beian: 
    # 是否显示备案信息
    enable: true
    # 是否在主页面最底下显示备案信息(虽然丑，但是完全满足规定要求)
    enableFooter: false
    # 备案号
    beianInfo: 鄂ICP备19018706号
    # 链接地址
    link: http://www.beian.miit.gov.cn

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否启用评论功能
    enable: true
    # 是否自动展开评论框
    autoExpand: true
    # 应用编号
    clientID: '5fdf535a821b025e256a'
    # 应用秘钥
    clientSecret: '173ad5d1c972a03d75f458097187960adffc8ed9'
    # issue仓库名
    repo: 'hongjun500.github.io'
    # Github名
    owner: 'hongjun500'
    # Github名
    admin: ['hongjun500']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: true


# 网站关键字
keywords: 鸿钧

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 

# 网站ico
favicon: /img/favicon.jpg

# rss文件
rss: atom.xml

# 百度sitemap
sitemap: 
  path: sitemap.xml
baidusitemap: 
  path: baidusitemap.xml

# 百度自动推送  
baidu_push: true